// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS-B-KQB2r4gHAAiAf3Rw8mMz27hPHFxE',
    appId: '1:54243215547:web:6d80527c52e6a78ec5819e',
    messagingSenderId: '54243215547',
    projectId: 'musify-e648e',
    authDomain: 'musify-e648e.firebaseapp.com',
    storageBucket: 'musify-e648e.appspot.com',
    measurementId: 'G-4G4BK09J6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkLc1QKUwfCf7fm2t2G_jLQUewdYJOAc',
    appId: '1:54243215547:android:d7d40cf01e89401fc5819e',
    messagingSenderId: '54243215547',
    projectId: 'musify-e648e',
    storageBucket: 'musify-e648e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsY9oOool2ud4WYb0LzfS8V6uDSRNvUgQ',
    appId: '1:54243215547:ios:36afc7169d24317fc5819e',
    messagingSenderId: '54243215547',
    projectId: 'musify-e648e',
    storageBucket: 'musify-e648e.appspot.com',
    iosBundleId: 'com.example.iiexMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsY9oOool2ud4WYb0LzfS8V6uDSRNvUgQ',
    appId: '1:54243215547:ios:92e1ee845e99f5c8c5819e',
    messagingSenderId: '54243215547',
    projectId: 'musify-e648e',
    storageBucket: 'musify-e648e.appspot.com',
    iosBundleId: 'com.example.iiexMusic.RunnerTests',
  );
}
